### ISSUE TITLE
Trigger Device Configuration Tool Code Generation

### ISSUE THREAD

**Issue by MattMoradi** [xanderhendriks/action-build-stm32cubeide#5]
Is it possible to pass arguments via YAML (or otherwise) to the docker container to trigger CubeIDE's code generator? CubeIDE triggers this automatically whenever changes are made to the IOC file or manually via `Project > Generate Code`

**Comment by MattMoradi** [comment]
According to the [user manual](https://www.st.com/resource/en/user_manual/um1718-stm32cubemx-for-stm32-configuration-and-initialization-c-code-generation-stmicroelectronics.pdf#page=36), MX accepts a `project generate` argument that seems applicable. These might also help:
https://community.st.com/s/question/0D53W000016PdpoSAC/solved-cubemx-run-code-generation-from-command-line
https://community.st.com/s/question/0D50X00009XkWE8SAN/stm32cube-generate-code-from-command-line-with-no-gui

**Comment by xanderhendriks** [comment]
Please have a look at the [entrypoint.sh](https://github.com/xanderhendriks/action-build-stm32cubeide/blob/master/entrypoint.sh) and let me know which commands I should add in order to make this work for you. In the links I only see hints to solutions. Some of them using CubeMX, which I don't think will be installed in this docker (Unless it is part of the STM32CubeIDE)
I'm happy to add some extra command option(s) to the github action, so it becomes useful for even more people. But I would need your help for that.
Easiest would be if you fork the repo, make and try your changes and then put in a pull request to get your changes merged into this repo. But I'm open to other solutions.

**Comment by xanderhendriks** [comment]
@MattMoradi were you able to find out the commands to be added to the entrypoint.sh? Or do you need some help?

**Comment by xanderhendriks** [comment]
@tniessen thanks for your feedback. I have written this action to automate the workflow for my clients. I shared it so other people can use it if they find it useful. I'm happy to make changes, but as mentioned [above](https://github.com/xanderhendriks/action-build-stm32cubeide/issues/5#issuecomment-1501029778) it would be great if people who have improvement ideas can help by sharing them with a Pull Request in the same way as I'm sharing what I needed to get the STM32 tools working for me in actions.
The way you mention that the CubeMX tool often doesn't work properly, I think it would require some investigation to see how a reliable flow can be guaranteed. There is nothing worse than committing your changes and than not being able to get them to be build by the action.
I agree that the ST tools don't seem to have been designed with command line use from the ground up, but I'm glad they have added support. If it is not working properly for you with CubeMX than I think it would be best to first ask ST to look into fixing the issues you have found, before integrating it here. But as long as we document it may not always work properly I'm happy to  accept a Pull Request to add this feature.
I did notice that ST seems to have made a lot of their [X-Cube](https://github.com/orgs/STMicroelectronics/repositories?q=x-cube-&type=all&language=&sort=) packages available through their github. So now you can use submodules to integrate them into your code. A great step forward.
Please let me know if you would like to create a Pull Request. Otherwise I'll close this issue as it doesn't seem to be big enough a problem for anyone to invest some time in it.

**Comment by xanderhendriks** [comment]
Closing as no one seems to have an interest in adding this feature and I currently have no use for it myself.
If someone else comes across this issue after it has been closed and would like to add this functionality then please go ahead and create a PR.
