### ISSUE TITLE
Option to set build configuration

### ISSUE THREAD

**Issue by mupfdev** [xanderhendriks/action-build-stm32cubeide#8]
Hello,
I'm currently using this workflow to build my project's firmware, however, because I use separate linker scripts for debug and release builds, I would need a way to set a different build configuration. Is this possible?

The idea is to use GitHub Actions to build and upload the firmware on every commit. Then the firmware can then be downloaded and flashed using WebUSB.

Any help is highly appreciated!

Best regards,
Michael

**Comment by xanderhendriks** [comment]
I required this feature myself a while back and had a look at how to add this. As it turned out it is already supported. I have been using it for some time now, but I never updated the documentation to indicate how this can be done.
I have updated the action.yml and the [readme.md](https://github.com/xanderhendriks/action-build-stm32cubeide#readme) to explain how to do this. Please have a look and try if you can manage to get it to work.

**Comment by mupfdev** [comment]
Works like a charm, thank you!
